OnlineShop/OnlineShop/Areas/Admin/Controllers/OderDetailController.cs
using Models.DAL;
using Models.FrameWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class OderDetailController : BaseController
    {
        [HttpGet]
        public ActionResult Index(string searchString, int page = 1, int pageSize = 5)
        {
            var dal = new OrderDetailDAL();
            ViewBag.SearchString = searchString;
            var model = dal.ListAllPaging(searchString,page, pageSize);
            return View(model);
        }

        //public ActionResult Insert()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Insert(oderdetail od)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var dal = new OrderDetailDAL();
        //        od.TrangThai = true;
        //        var result = dal.Insert(od);
        //        if (result == true)
        //        {
        //            return RedirectToAction("Index", "OderDetail");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "Thêm mới không thành công");
        //        }
        //    }
        //    return View("Index");

        //}
        //[HttpGet]
        //public ActionResult Edit()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Edit(oderdetail od)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var dal = new OrderDetailDAL();

        //        var result = dal.Update(od);
        //        if (result)
        //        {
        //            return RedirectToAction("Index", "OderDetail");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "Cập nhật không thành công");
        //        }
        //    }
        //    return View("Index");
        //}
        [HttpDelete]
        public ActionResult Delete(long Id)
        {
            new OrderDetailDAL().Delete(Id);
            return RedirectToAction("Index");
        }
    }
}

OnlineShop/OnlineShop/Areas/Admin/Views/OderDetail/Edit.cshtml
@model Models.FrameWork.oderdetail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{

    Thêm mới oderdetail.}

@using (Html.BeginForm("Edit", "OderDetail", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>oderdetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.hoten, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.hoten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.hoten, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.masp, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.masp, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.masp, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.soluong, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.giatien, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.giatien, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.giatien, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Create" class="btn btn-primary">
                    Cập nhật
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShop/OnlineShop/Areas/Admin/Views/OderDetail/Index.cshtml
@model PagedList.IPagedList<Models.FrameWork.oderdetail>

@using PagedList.Mvc
@{
    ViewBag.Title = "Quản lý tintuc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Danh sách oderdetail.}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách oderdetail</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Index", "OderDetail", FormMethod.Get))
        {
            <div class="row" style="margin-bottom:20px;">
                <div class="col-lg-5">
                    <div class="input-group">
                        <input type="text" value="@ViewBag.SearchString" name="searchString" class="form-control bg-light border-0 small" placeholder="Search for..."
                               aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        }
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Họ tên</th>
                        <th>Mã sản phẩm</th>
                        <th>Tên sản phẩm</th>
                        
                        <th>Số lượng</th>
                        <th>Giá tiền</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.ID">
                            <td>@item.hoten</td>
                            <td>@item.masp</td>
                            <td>@item.tensp</td>
                            <td>@item.soluong</td>
                            <td>@item.giatien</td>
                            

                            <td>
                                @*<a href="/Admin/OderDetail/Edit/@item.ID"><button type="button" class="btn btn-primary">Cập nhật</button></a>
                                |*@
                                <button type="button" class="btn btn-danger">
                                    @Ajax.ActionLink("Xoá", "Delete", new { @id = item.ID }, new AjaxOptions
                               {
                                   Confirm = "Bạn muốn xóa bản ghi này không",
                                   OnComplete = "$('#row_ " + item.ID + "').remove()",
                                   HttpMethod = "Delete"
                               })
                                </button>


                            </td>
                        </tr>

                    }

                </tbody>
            </table>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = ViewBag.SearchString }))
            @*<a href="/Admin/OderDetail/Insert"><button type="button" class="btn btn-primary">Thêm mới</button></a>*@
        </div>
    </div>
</div>

OnlineShop/OnlineShop/Areas/Admin/Views/OderDetail/Insert.cshtml
@model Models.FrameWork.oderdetail

@{
    ViewBag.Title = "Insert";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{

    Thêm mới oderdetail.}

@using (Html.BeginForm("Insert","OderDetail",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>oderdetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.hoten, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.hoten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.hoten, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.masp, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.masp, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.masp, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.soluong, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.giatien, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.giatien, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.giatien, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        

        

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Create" class="btn btn-primary">
                    Thêm mới
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>